export const commandList = [
  {
    name: 'DEPARTMENT OF RESEARCH AND PLANNING',
    code: '1-21',
    commandCategoryId: 0,
    lgaId: 0,
    stateId: 0,
  },
  {
    name: 'DEPARTMENT OF INFORMATION AND COMMUNICATION TECHNOLOGY',
    code: '1-22',
    commandCategoryId: 0,
    lgaId: 0,
    stateId: 0,
  },
  {
    name: 'DEPARTMENT OF LOGISTICS AND SUPPLY',
    code: '1-18',
    commandCategoryId: 0,
    lgaId: 0,
    stateId: 0,
  },
  {
    name: 'FORCE CRIMINAL INVESTIGATION DEPARTMENT',
    code: '1-19',
    commandCategoryId: 0,
    lgaId: 0,
    stateId: 0,
  },
  {
    name: 'DEPARTMENT OF TRAINING AND DEVELOPMENT',
    code: '1-20',
    commandCategoryId: 0,
    lgaId: 0,
    stateId: 0,
  },
  {
    name: 'OFFICE OF THE INSPECTOR-GENERAL OF POLICE',
    code: '1-15',
    commandCategoryId: 0,
    lgaId: 0,
    stateId: 0,
  },
  {
    name: 'DEPARTMENT OF FINANCE AND ADMINISTRATION',
    code: '1-16',
    commandCategoryId: 0,
    lgaId: 0,
    stateId: 0,
  },
  {
    name: 'DEPARTMENT OF OPERATIONS',
    code: '1-17',
    commandCategoryId: 0,
    lgaId: 0,
    stateId: 0,
  },
  {
    name: 'FORCE INTELLIGENCE DEPARTMENT',
    code: '1-23',
    commandCategoryId: 0,
    lgaId: 0,
    stateId: 0,
  },
  {
    name: 'FORCE SECRETARY',
    code: '1-73',
    commandCategoryId: 0,
    lgaId: 0,
    stateId: 0,
  },
];
