export const counterTerrorismList = [
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 1 - KUJE ABUJA, FCT',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 237,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 10 - ENUGU, Enugu',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 246,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 11 - JOS, Plateau',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 247,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 12 - MINNA, Niger',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 248,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 13 - KANO, Kano',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 249,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 14 - YOLA, Adamawa',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 250,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 15 - IBADAN, Oyo',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 251,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 16 - MAKURDI, Benue',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 252,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 17 - LOKOJA, Kogi',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 253,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 18 - GUSAU, Zamfara',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 254,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 19 - GOMBE, Gombe',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 255,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 2 - IKEJA, Lagos',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 238,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 20 - LAFIA, Nasarawa',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 256,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 21 - ILORIN, Kwara',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 257,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 22 - TORORUWA, Bayelsa',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 258,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 23 - uyo, Akwa Ibom',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 259,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 24 - NIGERIA POLICE FORCE HEADQUARTERS LOUIS EDET HOUSE SHEHU SHAGARI WAY ABUJA, FCT',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 260,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 25 - OKIJA, Anambra',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 261,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 26 - KADUNA, Kaduna',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 262,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 3 - RUMUAGHOLU PORT HARCOURT, Rivers',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 239,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 4 - ABA , Abia',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 240,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 5 - WARRI, Delta',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 241,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 6 - DAMATURU, Yobe',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 242,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 7 - OWERRI, Imo',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 243,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 8 - MAIDUGURI, Borno',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 244,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU BASE 9 - BAUCHI, Bauchi',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 245,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'COUNTER-TERRORISM UNIT - CTU HEADQUARTERS - NIGERIA POLICE FORCE HEADQUARTERS LOUIS EDET HOUSE SHEHU SHAGARI WAY ABUJA, FCT',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 236,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
];
