export const explosiveODList = [
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 1 - CENTRAL STORES MOBOLAJI BANK-ANTHONY WAY IKEJA, Lagos',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2135,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 11 - ILORIN, Kwara',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2142,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 12 - ABEOKUTA, Ogun',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2143,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 14 - JOS, Plateau',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2144,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 15 - SOKOTO, Sokoto',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2145,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 16 - OSOGBO, Osun',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2127,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 17 - MAKURDI, Benue',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2128,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 18 - AKURE, Ondo',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2146,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 19 - IBADAN, Oyo',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2147,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 2 - OWERRI, Imo',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2136,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 20 - KATSINA, Katsina',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2148,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 21 - POLICE AREA COMMAND WARRI, Delta',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2149,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 22 - YENAGOA, Bayelsa',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2150,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 23 - IKEJA, Lagos',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2151,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 24 - DUTSE, Jigawa',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2152,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 25 - GUSAU, Zamfara',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2129,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 26 - BIRNIN KEBBI, Kebbi',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2153,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 27 - LAFIA, Nasarawa',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2154,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 3 - ENUGU, Enugu',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2137,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 31 - BAUCHI, Bauchi',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2130,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 32 - MINNA, Niger',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2155,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 33 - LOKOJA, Kogi',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2131,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 34 - ADO EKITI, Ekiti',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2132,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 35 - ABAKALIKI, Ebonyi',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2133,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 36 - AWKA, Anambra',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2156,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 37 - UMUAHIA, Abia',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2157,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 38 - UYO, Akwa Ibom',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2134,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 4 - CALABAR, Cross River',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2138,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 5 - KADUNA, Kaduna',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2139,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 6 - PORT HARCOURT, Rivers',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2140,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 7 - OREDO, Edo',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2125,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 8 - KANO, Kano',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2126,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'EXPLOSIVE ORDINANCE DISPOSAL (EOD) - EOD BASE 9 - LADOKE AKINTOLA BOULEVARD GARKI ABUJA, FCT',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 2141,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
];
