export const guardServiceList = [
  {
    Id: 22,
    ParentId: 18,
    Name: 'Bank',
    ParentName: null,
    MinimumRequiredOfficers: 2,
    ShowExtraFields: false,
  },
  {
    Id: 23,
    ParentId: 18,
    Name: 'Private Company',
    ParentName: null,
    MinimumRequiredOfficers: 2,
    ShowExtraFields: false,
  },
  {
    Id: 24,
    ParentId: 18,
    Name: 'Religious Body',
    ParentName: null,
    MinimumRequiredOfficers: 2,
    ShowExtraFields: false,
  },
  {
    Id: 26,
    ParentId: 18,
    Name: 'Individual & Private Residence',
    ParentName: null,
    MinimumRequiredOfficers: 2,
    ShowExtraFields: false,
  },
  {
    Id: 28,
    ParentId: 18,
    Name: 'Multinational Corporation',
    ParentName: null,
    MinimumRequiredOfficers: 2,
    ShowExtraFields: false,
  },
  {
    Id: 31,
    ParentId: 18,
    Name: 'Non-Governmental Organizations',
    ParentName: null,
    MinimumRequiredOfficers: 2,
    ShowExtraFields: false,
  },
  {
    Id: 33,
    ParentId: 18,
    Name: 'Oil Protection',
    ParentName: null,
    MinimumRequiredOfficers: 2,
    ShowExtraFields: false,
  },
  {
    Id: 35,
    ParentId: 18,
    Name: 'Event',
    ParentName: null,
    MinimumRequiredOfficers: 2,
    ShowExtraFields: false,
  },
];
