export const policeMobileForceList = [
  {
    Name: 'POLICE MOBILE FORCE - 1 PMF SQUADRON - KADUNA, Kaduna',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 163,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 10 PMF SQUADRON - BAUCHI, Bauchi',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 143,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 11 PMF SQUADRON - CALABAR, Cross River',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 148,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 12 PMF SQUADRON - MINNA, Niger',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 178,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 13 PMF SQUADRON - MAKURDI, Benue',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 145,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 14 PMF SQUADRON - YOLA, Adamawa',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 136,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 15 PMF SQUADRON - ILORIN, Kwara',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 171,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 16 PMF SQUADRON - OKE ILEWO ABEOKUTA, Ogun',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 180,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 17 PMF SQUADRON - AKURE, Ondo',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 181,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 18 PMF SQUADRON - OWERRI, Imo',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 160,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 19 PMF SQUADRON - PORT HARCOURT, Rivers',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 186,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 2 PMF SQUADRON - KEFFI ROAD OBALENDE LAGOS, Lagos',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 130,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 20 PMF SQUADRON - IKEJA, Lagos',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 172,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 21 PMF SQUADRON - NYANYA, FCT',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 156,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 22 PMF SQUADRON - IKEJA, Lagos',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 173,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 23 PMF SQUADRON - OBALENDE LAGOS, Lagos',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 131,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 24 PMF SQUADRON - PRESCORT PRESIDENTIAL VILLA ABUJA, FCT',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 126,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 25 PMF SQUADRON - IWUKEM AZUMINI ABIA, Abia',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 133,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 26 PMF SQUADRON - UYO, Akwa Ibom',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 138,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 27 PMF SQUADRON - KATSINA, Katsina',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 168,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 28 PMF SQUADRON - UMUAHIA ABIA, Abia',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 134,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 29 PMF SQUADRON - AWKA, Anambra',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 141,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 3 PMF SQUADRON - ENUGU, Enugu',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 155,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 30 PMF SQUADRON - YENAGOA, Bayelsa',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 144,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 31 PMF SQUADRON - ASABA, Delta',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 149,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 32 PMF SQUADRON - ABAKALIKI, Ebonyi',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 151,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 33 PMF SQUADRON - ADO-EKITI, Ekiti',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 154,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 34 PMF SQUADRON - GOMBE, Gombe',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 158,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 35 PMF SQUADRON - DUTSE, Jigawa',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 162,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 36 PMF SQUADRON - BIRNIN-KEBBI, Kebbi',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 169,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 37 PMF SQUADRON - LOKOJA, Kogi',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 170,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 38 PMF SQUADRON - AKWANGA, Nasarawa',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 176,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 39 PMF SQUADRON - OSOGBO, Osun',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 182,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 4 PMF SQUADRON - IBADAN, Oyo',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 183,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 40 PMF SQUADRON - JALINGO, Taraba',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 190,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 41 PMF SQUADRON - DAMATURU, Yobe',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 192,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 42 PMF SQUADRON - GUSAU, Zamfara',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 193,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 43 PMF SQUADRON - LION BUILDING LAGOS, Lagos',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 132,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 44 PMF SQUADRON - NIGERIA POLICE FORCE HEADQUARTERS LOUIS EDET HOUSE SHEHU SHAGARI WAY ABUJA, FCT',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 127,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 45 PMF SQUADRON - NIGERIA POLICE FORCE HEADQUARTERS AREA 10 ABUJA, FCT',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 128,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 46 PMF SQUADRON - NIGERIA POLICE FORCE HEADQUARTERS LOUIS EDET HOUSE SHEHU SHAGARI WAY ABUJA, FCT',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 129,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 47 PMF SQUADRON - ZARIA, Kaduna',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 164,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 48 PMF SQUADRON - AHOADA, Rivers',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 187,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 49 PMF SQUADRON - EPE, Lagos',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 174,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 5 PMF SQUADRON - BENIN, Edo',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 152,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 50 PMF SQUADRON - KUBWA, FCT',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 157,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 51 PMF SQUADRON - OGHARA, Delta',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 150,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 52 PMF SQUADRON - CHALLAWA, Kano',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 167,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 53 PMF SQUADRON - BAMA, Borno',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 147,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 54 PMF SQUADRON - ONITSHA, Anambra',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 142,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 55 PMF SQUADRON - ABA ABIA, Abia',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 135,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 56 PMF SQUADRON - OGONI, Rivers',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 188,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 57 PMF SQUADRON - UKANA, Akwa Ibom',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 139,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 58 PMF SQUADRON - LAFIA, Nasarawa',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 177,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 59 PMF SQUADRON - BAJOGA, Gombe',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 159,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 6 PMF SQUADRON - MAIDUGURI, Borno',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 146,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 60 PMF SQUADRON - IYAMHO, Edo',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 153,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 61 PMF SQUADRON - NIGER HOLY LAND KONTAGORA, Niger',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 179,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 62 PMF SQUADRON - KAFANCHAN, Kaduna',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 165,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 63 PMF SQUADRON - IKORODU, Lagos',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 175,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 64 PMF SQUADRON - IDEATO, Imo',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 161,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 65 PMF SQUADRON - MUBI, Adamawa',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 137,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 66 PMF SQUADRON - SHENDAM, Plateau',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 185,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 67 PMF SQUADRON - TAKUM, Taraba',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 191,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 68 PMF SQUADRON - OFFA, Kwara',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 140,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 69 PMF SQUADRON - TOTO, Nasarawa',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 194,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 7 PMF SQUADRON - SOKOTO, Sokoto',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 189,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 70 PMF SQUADRON - KABBA, Kogi',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 195,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 71 PMF SQUADRON - AWA-IJEBU, Ogun',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 196,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 72 PMF SQUADRON - AGO ARE, Oyo',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 197,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 73 PMF SQUADRON - MAGUMERI, Borno',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 198,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 74 PMF SQUADRON - DAMBOA, Borno',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 199,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 75 PMF SQUADRON - OBUDU, Cross River',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 200,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 76 PMF SQUADRON - NSUKKA, Enugu',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 201,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 77 PMF SQUADRON - OKENE, Kogi',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 202,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 78 PMF SQUADRON - MARADUN, Zamfara',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 203,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 79 PMF SQUADRON - BONI-GARI, Yobe',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 204,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 8 PMF SQUADRON - JOS, Plateau',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 184,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - 9 PMF SQUADRON - KANO, Kano',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 166,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'POLICE MOBILE FORCE - PMF HEADQUARTERS - NIGERIA POLICE FORCE HEADQUARTERS LOUIS EDET HOUSE SHEHU SHAGARI WAY ABUJA, FCT',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 125,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
];
