export const specialProtectionServiceList = [
  {
    Id: 19,
    ParentId: 16,
    Name: 'Orderly',
    ParentName: null,
    MinimumRequiredOfficers: 1,
    ShowExtraFields: false,
  },
  {
    Name: 'DEPARTMENT OF OPERATIONS - COUNTER-TERRORISM UNIT',
    Code: '1-17-93',
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 235,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 2,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'DEPARTMENT OF OPERATIONS - SPECIAL PROTECTION UNIT',
    Code: '1-17-88',
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 208,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 2,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'DEPARTMENT OF OPERATIONS - POLICE MOBILE FORCE',
    Code: '1-17-38',
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 124,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 2,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'DEPARTMENT OF OPERATIONS - EXPLOSIVE ORDINANCE DISPOSAL (EOD)',
    Code: '1-17-24',
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 113,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 2,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
];
