export const specialProtectionUnitList = [
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 1 - KANO, Kano',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 210,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 10 - SOKOTO, Sokoto',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 219,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 11 - OSOGBO, Osun',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 220,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 12 - BAUCHI, Bauchi',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 221,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 13 - ABEOKUTA, Ogun',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 222,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 14 - AKURE, Ondo',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 223,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 15 - AWKA, Anambra',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 224,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 16 - IKEJA, Lagos',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 225,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 17 - IKEJA, Lagos',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 226,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 18 - IKEJA, Lagos',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 227,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 19 - PORT-HARCOURT, Rivers',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 228,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 2 - IKEJA, Lagos',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 211,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 20 - NATIONAL ASSEMBLY COMPLEX ABUJA, FCT',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 229,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 21 - ENUGU, Enugu',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 230,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 22 - IBADAN, Oyo',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 231,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 24 - CALABAR, Cross River',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 232,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 25 - ASABA, Delta',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 233,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 26 - ABAKALIKI, Ebonyi',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 234,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 3 - YOLA, Adamawa',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 212,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 4 - MAKURDI, Benue',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 213,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 5 - BENIN CITY, Edo',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 214,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 6 - PORT HARCOURT, Rivers',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 215,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 7 - ABUJA, FCT',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 216,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 8 - LOKOJA, Kogi',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 217,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU BASE 9 - UMUAHIA, Abia',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 218,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
  {
    Name: 'SPECIAL PROTECTION UNIT - SPU HEADQUARTERS - NIGERIA POLICE FORCE HEADQUARTERS LOUIS EDET HOUSE SHEHU SHAGARI WAY ABUJA, FCT',
    Code: null,
    CommandCategoryId: 0,
    LGAId: 0,
    StateId: 0,
    Id: 209,
    LGAName: null,
    StateName: null,
    Address: null,
    CommandTypeId: 0,
    SelectAllSections: false,
    SelectAllSubSections: false,
  },
];
